name: neuralmrf
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.13
  - pip
  - pip:
      - numpy==1.22.4
      - pandas==1.4.2
      - einops==0.4.1
      - scipy==1.8.1
      - cvxpy==1.2.1
      - matplotlib==3.7.1
      - seaborn==0.12.2
      - scikit-learn==1.1.1
      - biopython==1.79
      - tqdm==4.64.0
      - pyyaml==6.0
